#!/bin/bash
#
#
echo "Sisesta ringi raadius (CM)"
read raadius
echo "sisesta pi"
read pi
#
r2=`expr $raadius \* $raadius`
pindala=`$pi \* $r2`
diameeter=`$raadius \* $raadius`
ymbermoot=`$pi \* $diameeter`
#
#
echo "Sinu ringi pindala on $pindala cm ja ümbermõõt $ymbermoot cm"
#
# lõpp 
