#!/bin/bash
#
#
echo "Sisesta ringi raadius (CM)"
read raadius
#
ymbermoot=$(echo "$raadius * 2 * 3.14" | bc )
pindala=$(echo "$raadius ^ 2 * 3.14" | bc )
#
echo "Sinu ringi pindala on $pindala cm ja ümbermõõt $ymbermoot cm"
#
# lõpp 
