#!/bin/bash
#
# bussireisid
echo -n "Mitu reisijat on sinu grupis? " #küsib, palju reisijaid on
read reisijad #loeb vastust
echo -n "Mitu kohta on Teie bussis? " #küsib, palju kohti on bussis
read kohad #loeb kohti
#
buss=`expr $reisijad / $kohad` #määrab $bussile väärtuse
ylej22nud=`expr $reisijad % $kohad` #määrab $ylej22nud väärtuse
if test $ylej22nud -gt 0 #kui jääk on suurem kui 0
then
buss=$(($buss + 1)) #lisab lõppvastusele +1 .
fi
echo "Täielikult täidetud busse on $buss ja yle jaab $ylej22nud inimest "
# annab kasutajale lõppvastuse
#
