#!/bin/bash
# for tsükli näide
for ((  arv=1; arv<11; arv++ ))
do
jaak=$(($arv % 2 ))
if [ $jaak -eq 0 ]; then
summa=$(($summa + $arv))
echo $summa
fi
done
echo "Arvude vahemikus 1 kuni 10 paariarvude summa on: $summa"""
# end
