#!/bin/bash
# liitmine
echo -n "Sisesta yks taisarv: "
read arv
summa=0
while [ $arv -ne 0 ]
do
jaak=$(($arv % 10 ))
summa=$(($summa + $jaak))
arv=$(($arv / 10 ))
done
echo "Sinu arvude summa on: $summa. "
