#!/bin/bash
#
# otsimisskript
find /var/ -name "*.log" 2>/dev/null -exec wc -1 {} | sort -nr #leiab /var/ kataloogist failid .log lõpuga ning sorteerib need numbrilises järjekorras (sort -nr)
#
#
# lõpp

